name: smart_home
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  mqtt_client: ^10.2.1
  typed_data: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/